import type { NavItem } from "@/lib/nav";
import {
  LayoutDashboard,
  Bot,
  ShoppingCart,
  History,
  Package,
  Tags,
  Boxes,
  ArrowLeftRight,
  ShoppingBag,
  Users,
  CreditCard,
  Truck,
  ClipboardList,
  Globe,
  BarChart3,
  Store,
  UserCog,
  Settings,
  Receipt,
  Wallet,
  FileText,
  LifeBuoy,
  ShoppingBasket,
  Bike,
  FileSignature,
  IdCard,
  Award,
  Crown,
  Bell,
  BellRing,
  PackagePlus,
  Calculator,
  Images,
  CalendarClock,
  Zap,
  Send,
  Package2,
  Banknote,
  Stethoscope,
  Activity,
} from "lucide-react";

// Module simple (sans "use client") pour que cette table icône-par-module
// puisse être importée aussi bien par des composants client (SidebarLink)
// que par des composants serveur (ModulesGuide sur la page Aide) : un
// composant/objet exporté depuis un module "use client" devient une
// référence client opaque, illisible (indexation cassée à l'exécution) une
// fois importé côté serveur — d'où ce fichier neutre séparé.
// Couleur du badge derrière chaque icône de module (accent visuel façon
// FasoStock — un point de couleur distinct par module pour repérer vite un
// module dans une longue liste). Purement décoratif : le rouge/l'amber
// restent réservés aux états sémantiques danger/attention, donc absents ici.
const BADGE_PALETTE = [
  "bg-orange-500",
  "bg-purple-500",
  "bg-teal-500",
  "bg-sky-500",
  "bg-emerald-500",
  "bg-pink-500",
  "bg-indigo-500",
  "bg-cyan-500",
  "bg-rose-500",
  "bg-lime-600",
  "bg-violet-500",
  "bg-fuchsia-500",
  "bg-blue-500",
] as const;

const ICON_KEYS_ORDER: NavItem["icon"][] = [
  "dashboard",
  "assistant",
  "sales",
  "invoices",
  "products",
  "categories",
  "brands",
  "stock",
  "transfers",
  "purchases",
  "expenses",
  "customers",
  "credits",
  "suppliers",
  "inventory",
  "history",
  "cash-sessions",
  "history-global",
  "reports",
  "locations",
  "users",
  "settings",
  "support",
  "online-store",
  "vehicle-sales",
  "quotes",
  "vehicle-registration",
  "subscription",
  "notifications",
  "credit-reminders",
  "restock",
  "cost-price",
  "product-photos",
  "rentals",
  "quick-supply",
  "pickups",
  "shipments",
  "cashier",
  "consultations",
  "medical-stats",
];

export const ICON_BADGE_COLORS: Record<NavItem["icon"], string> = Object.fromEntries(
  ICON_KEYS_ORDER.map((key, index) => [key, BADGE_PALETTE[index % BADGE_PALETTE.length]])
) as Record<NavItem["icon"], string>;

export const NAV_ICONS: Record<NavItem["icon"], React.ComponentType<{ className?: string }>> = {
  dashboard: LayoutDashboard,
  assistant: Bot,
  sales: ShoppingCart,
  invoices: FileText,
  products: Package,
  categories: Tags,
  brands: Award,
  stock: Boxes,
  transfers: ArrowLeftRight,
  purchases: ShoppingBag,
  expenses: Receipt,
  customers: Users,
  credits: CreditCard,
  suppliers: Truck,
  inventory: ClipboardList,
  history: History,
  "cash-sessions": Wallet,
  "history-global": Globe,
  reports: BarChart3,
  locations: Store,
  users: UserCog,
  settings: Settings,
  support: LifeBuoy,
  "online-store": ShoppingBasket,
  "vehicle-sales": Bike,
  quotes: FileSignature,
  "vehicle-registration": IdCard,
  subscription: Crown,
  notifications: Bell,
  "credit-reminders": BellRing,
  restock: PackagePlus,
  "cost-price": Calculator,
  "product-photos": Images,
  rentals: CalendarClock,
  "quick-supply": Zap,
  pickups: Send,
  shipments: Package2,
  cashier: Banknote,
  consultations: Stethoscope,
  "medical-stats": Activity,
};
