// Pays du monde (source : GeoNames, countryInfo.txt) : [code ISO, indicatif, monnaie ISO, capitale].
// Les noms français et anglais viennent d’Intl.DisplayNames (voir lib/countries.ts).
export const WORLD_COUNTRIES: [code: string, dialCode: string, currency: string, capital: string][] = [
  ["AD", "+376", "EUR", "Andorra la Vella"],
  ["AE", "+971", "AED", "Abu Dhabi"],
  ["AF", "+93", "AFN", "Kabul"],
  ["AG", "+1", "XCD", "St. John's"],
  ["AI", "+1", "XCD", "The Valley"],
  ["AL", "+355", "ALL", "Tirana"],
  ["AM", "+374", "AMD", "Yerevan"],
  ["AO", "+244", "AOA", "Luanda"],
  ["AQ", "", "", ""],
  ["AR", "+54", "ARS", "Buenos Aires"],
  ["AS", "+1", "USD", "Pago Pago"],
  ["AT", "+43", "EUR", "Vienna"],
  ["AU", "+61", "AUD", "Canberra"],
  ["AW", "+297", "AWG", "Oranjestad"],
  ["AX", "+358", "EUR", "Mariehamn"],
  ["AZ", "+994", "AZN", "Baku"],
  ["BA", "+387", "BAM", "Sarajevo"],
  ["BB", "+1", "BBD", "Bridgetown"],
  ["BD", "+880", "BDT", "Dhaka"],
  ["BE", "+32", "EUR", "Brussels"],
  ["BF", "+226", "XOF", "Ouagadougou"],
  ["BG", "+359", "BGN", "Sofia"],
  ["BH", "+973", "BHD", "Manama"],
  ["BI", "+257", "BIF", "Gitega"],
  ["BJ", "+229", "XOF", "Porto-Novo"],
  ["BL", "+590", "EUR", "Gustavia"],
  ["BM", "+1", "BMD", "Hamilton"],
  ["BN", "+673", "BND", "Bandar Seri Begawan"],
  ["BO", "+591", "BOB", "Sucre"],
  ["BQ", "+599", "USD", ""],
  ["BR", "+55", "BRL", "Brasilia"],
  ["BS", "+1", "BSD", "Nassau"],
  ["BT", "+975", "BTN", "Thimphu"],
  ["BV", "", "NOK", ""],
  ["BW", "+267", "BWP", "Gaborone"],
  ["BY", "+375", "BYN", "Minsk"],
  ["BZ", "+501", "BZD", "Belmopan"],
  ["CA", "+1", "CAD", "Ottawa"],
  ["CC", "+61", "AUD", "West Island"],
  ["CD", "+243", "CDF", "Kinshasa"],
  ["CF", "+236", "XAF", "Bangui"],
  ["CG", "+242", "XAF", "Brazzaville"],
  ["CH", "+41", "CHF", "Bern"],
  ["CI", "+225", "XOF", "Yamoussoukro"],
  ["CK", "+682", "NZD", "Avarua"],
  ["CL", "+56", "CLP", "Santiago"],
  ["CM", "+237", "XAF", "Yaounde"],
  ["CN", "+86", "CNY", "Beijing"],
  ["CO", "+57", "COP", "Bogota"],
  ["CR", "+506", "CRC", "San Jose"],
  ["CU", "+53", "CUP", "Havana"],
  ["CV", "+238", "CVE", "Praia"],
  ["CW", "+599", "XCG", " Willemstad"],
  ["CX", "+61", "AUD", "Flying Fish Cove"],
  ["CY", "+357", "EUR", "Nicosia"],
  ["CZ", "+420", "CZK", "Prague"],
  ["DE", "+49", "EUR", "Berlin"],
  ["DJ", "+253", "DJF", "Djibouti"],
  ["DK", "+45", "DKK", "Copenhagen"],
  ["DM", "+1", "XCD", "Roseau"],
  ["DO", "+1", "DOP", "Santo Domingo"],
  ["DZ", "+213", "DZD", "Algiers"],
  ["EC", "+593", "USD", "Quito"],
  ["EE", "+372", "EUR", "Tallinn"],
  ["EG", "+20", "EGP", "Cairo"],
  ["EH", "+212", "MAD", "El-Aaiun"],
  ["ER", "+291", "ERN", "Asmara"],
  ["ES", "+34", "EUR", "Madrid"],
  ["ET", "+251", "ETB", "Addis Ababa"],
  ["FI", "+358", "EUR", "Helsinki"],
  ["FJ", "+679", "FJD", "Suva"],
  ["FK", "+500", "FKP", "Stanley"],
  ["FM", "+691", "USD", "Palikir"],
  ["FO", "+298", "DKK", "Torshavn"],
  ["FR", "+33", "EUR", "Paris"],
  ["GA", "+241", "XAF", "Libreville"],
  ["GB", "+44", "GBP", "London"],
  ["GD", "+1", "XCD", "St. George's"],
  ["GE", "+995", "GEL", "Tbilisi"],
  ["GF", "+594", "EUR", "Cayenne"],
  ["GG", "+44", "GBP", "St Peter Port"],
  ["GH", "+233", "GHS", "Accra"],
  ["GI", "+350", "GIP", "Gibraltar"],
  ["GL", "+299", "DKK", "Nuuk"],
  ["GM", "+220", "GMD", "Banjul"],
  ["GN", "+224", "GNF", "Conakry"],
  ["GP", "+590", "EUR", "Basse-Terre"],
  ["GQ", "+240", "XAF", "Ciudad de la Paz"],
  ["GR", "+30", "EUR", "Athens"],
  ["GS", "", "GBP", "Grytviken"],
  ["GT", "+502", "GTQ", "Guatemala City"],
  ["GU", "+1", "USD", "Hagatna"],
  ["GW", "+245", "XOF", "Bissau"],
  ["GY", "+592", "GYD", "Georgetown"],
  ["HK", "+852", "HKD", "Hong Kong"],
  ["HM", "", "AUD", ""],
  ["HN", "+504", "HNL", "Tegucigalpa"],
  ["HR", "+385", "EUR", "Zagreb"],
  ["HT", "+509", "HTG", "Port-au-Prince"],
  ["HU", "+36", "HUF", "Budapest"],
  ["ID", "+62", "IDR", "Jakarta"],
  ["IE", "+353", "EUR", "Dublin"],
  ["IL", "+972", "ILS", "Jerusalem"],
  ["IM", "+44", "GBP", "Douglas"],
  ["IN", "+91", "INR", "New Delhi"],
  ["IO", "+246", "USD", "Diego Garcia"],
  ["IQ", "+964", "IQD", "Baghdad"],
  ["IR", "+98", "IRR", "Tehran"],
  ["IS", "+354", "ISK", "Reykjavik"],
  ["IT", "+39", "EUR", "Rome"],
  ["JE", "+44", "GBP", "Saint Helier"],
  ["JM", "+1", "JMD", "Kingston"],
  ["JO", "+962", "JOD", "Amman"],
  ["JP", "+81", "JPY", "Tokyo"],
  ["KE", "+254", "KES", "Nairobi"],
  ["KG", "+996", "KGS", "Bishkek"],
  ["KH", "+855", "KHR", "Phnom Penh"],
  ["KI", "+686", "AUD", "Tarawa"],
  ["KM", "+269", "KMF", "Moroni"],
  ["KN", "+1", "XCD", "Basseterre"],
  ["KP", "+850", "KPW", "Pyongyang"],
  ["KR", "+82", "KRW", "Seoul"],
  ["XK", "", "EUR", "Pristina"],
  ["KW", "+965", "KWD", "Kuwait City"],
  ["KY", "+1", "KYD", "George Town"],
  ["KZ", "+7", "KZT", "Nur-Sultan"],
  ["LA", "+856", "LAK", "Vientiane"],
  ["LB", "+961", "LBP", "Beirut"],
  ["LC", "+1", "XCD", "Castries"],
  ["LI", "+423", "CHF", "Vaduz"],
  ["LK", "+94", "LKR", "Colombo"],
  ["LR", "+231", "LRD", "Monrovia"],
  ["LS", "+266", "LSL", "Maseru"],
  ["LT", "+370", "EUR", "Vilnius"],
  ["LU", "+352", "EUR", "Luxembourg"],
  ["LV", "+371", "EUR", "Riga"],
  ["LY", "+218", "LYD", "Tripoli"],
  ["MA", "+212", "MAD", "Rabat"],
  ["MC", "+377", "EUR", "Monaco"],
  ["MD", "+373", "MDL", "Chisinau"],
  ["ME", "+382", "EUR", "Podgorica"],
  ["MF", "+590", "EUR", "Marigot"],
  ["MG", "+261", "MGA", "Antananarivo"],
  ["MH", "+692", "USD", "Majuro"],
  ["MK", "+389", "MKD", "Skopje"],
  ["ML", "+223", "XOF", "Bamako"],
  ["MM", "+95", "MMK", "Nay Pyi Taw"],
  ["MN", "+976", "MNT", "Ulaanbaatar"],
  ["MO", "+853", "MOP", "Macao"],
  ["MP", "+1", "USD", "Saipan"],
  ["MQ", "+596", "EUR", "Fort-de-France"],
  ["MR", "+222", "MRU", "Nouakchott"],
  ["MS", "+1", "XCD", "Plymouth"],
  ["MT", "+356", "EUR", "Valletta"],
  ["MU", "+230", "MUR", "Port Louis"],
  ["MV", "+960", "MVR", "Male"],
  ["MW", "+265", "MWK", "Lilongwe"],
  ["MX", "+52", "MXN", "Mexico City"],
  ["MY", "+60", "MYR", "Kuala Lumpur"],
  ["MZ", "+258", "MZN", "Maputo"],
  ["NA", "+264", "NAD", "Windhoek"],
  ["NC", "+687", "XPF", "Noumea"],
  ["NE", "+227", "XOF", "Niamey"],
  ["NF", "+672", "AUD", "Kingston"],
  ["NG", "+234", "NGN", "Abuja"],
  ["NI", "+505", "NIO", "Managua"],
  ["NL", "+31", "EUR", "Amsterdam"],
  ["NO", "+47", "NOK", "Oslo"],
  ["NP", "+977", "NPR", "Kathmandu"],
  ["NR", "+674", "AUD", "Yaren"],
  ["NU", "+683", "NZD", "Alofi"],
  ["NZ", "+64", "NZD", "Wellington"],
  ["OM", "+968", "OMR", "Muscat"],
  ["PA", "+507", "PAB", "Panama City"],
  ["PE", "+51", "PEN", "Lima"],
  ["PF", "+689", "XPF", "Papeete"],
  ["PG", "+675", "PGK", "Port Moresby"],
  ["PH", "+63", "PHP", "Manila"],
  ["PK", "+92", "PKR", "Islamabad"],
  ["PL", "+48", "PLN", "Warsaw"],
  ["PM", "+508", "EUR", "Saint-Pierre"],
  ["PN", "+870", "NZD", "Adamstown"],
  ["PR", "+1", "USD", "San Juan"],
  ["PS", "+970", "ILS", "East Jerusalem"],
  ["PT", "+351", "EUR", "Lisbon"],
  ["PW", "+680", "USD", "Melekeok"],
  ["PY", "+595", "PYG", "Asuncion"],
  ["QA", "+974", "QAR", "Doha"],
  ["RE", "+262", "EUR", "Saint-Denis"],
  ["RO", "+40", "RON", "Bucharest"],
  ["RS", "+381", "RSD", "Belgrade"],
  ["RU", "+7", "RUB", "Moscow"],
  ["RW", "+250", "RWF", "Kigali"],
  ["SA", "+966", "SAR", "Riyadh"],
  ["SB", "+677", "SBD", "Honiara"],
  ["SC", "+248", "SCR", "Victoria"],
  ["SD", "+249", "SDG", "Khartoum"],
  ["SS", "+211", "SSP", "Juba"],
  ["SE", "+46", "SEK", "Stockholm"],
  ["SG", "+65", "SGD", "Singapore"],
  ["SH", "+290", "SHP", "Jamestown"],
  ["SI", "+386", "EUR", "Ljubljana"],
  ["SJ", "+47", "NOK", "Longyearbyen"],
  ["SK", "+421", "EUR", "Bratislava"],
  ["SL", "+232", "SLE", "Freetown"],
  ["SM", "+378", "EUR", "San Marino"],
  ["SN", "+221", "XOF", "Dakar"],
  ["SO", "+252", "SOS", "Mogadishu"],
  ["SR", "+597", "SRD", "Paramaribo"],
  ["ST", "+239", "STN", "Sao Tome"],
  ["SV", "+503", "USD", "San Salvador"],
  ["SX", "+599", "XCG", "Philipsburg"],
  ["SY", "+963", "SYP", "Damascus"],
  ["SZ", "+268", "SZL", "Mbabane"],
  ["TC", "+1", "USD", "Cockburn Town"],
  ["TD", "+235", "XAF", "N'Djamena"],
  ["TF", "", "EUR", "Port-aux-Francais"],
  ["TG", "+228", "XOF", "Lome"],
  ["TH", "+66", "THB", "Bangkok"],
  ["TJ", "+992", "TJS", "Dushanbe"],
  ["TK", "+690", "NZD", ""],
  ["TL", "+670", "USD", "Dili"],
  ["TM", "+993", "TMT", "Ashgabat"],
  ["TN", "+216", "TND", "Tunis"],
  ["TO", "+676", "TOP", "Nuku'alofa"],
  ["TR", "+90", "TRY", "Ankara"],
  ["TT", "+1", "TTD", "Port of Spain"],
  ["TV", "+688", "AUD", "Funafuti"],
  ["TW", "+886", "TWD", "Taipei"],
  ["TZ", "+255", "TZS", "Dodoma"],
  ["UA", "+380", "UAH", "Kyiv"],
  ["UG", "+256", "UGX", "Kampala"],
  ["UM", "+1", "USD", ""],
  ["US", "+1", "USD", "Washington"],
  ["UY", "+598", "UYU", "Montevideo"],
  ["UZ", "+998", "UZS", "Tashkent"],
  ["VA", "+379", "EUR", "Vatican City"],
  ["VC", "+1", "XCD", "Kingstown"],
  ["VE", "+58", "VES", "Caracas"],
  ["VG", "+1", "USD", "Road Town"],
  ["VI", "+1", "USD", "Charlotte Amalie"],
  ["VN", "+84", "VND", "Hanoi"],
  ["VU", "+678", "VUV", "Port Vila"],
  ["WF", "+681", "XPF", "Mata Utu"],
  ["WS", "+685", "WST", "Apia"],
  ["YE", "+967", "YER", "Sanaa"],
  ["YT", "+262", "EUR", "Mamoudzou"],
  ["ZA", "+27", "ZAR", "Pretoria"],
  ["ZM", "+260", "ZMW", "Lusaka"],
  ["ZW", "+263", "ZWG", "Harare"],
  ["CS", "+381", "RSD", "Belgrade"],
  ["AN", "+599", "ANG", "Willemstad"],
];
