// Pays et monnaies du monde (source : GeoNames, countryInfo.txt ; noms : Intl, figés ici).
// Noms écrits une fois pour toutes : le serveur et le navigateur affichent exactement le
// même texte (leurs bibliothèques de langue diffèrent parfois, ce qui cassait l’hydratation).

/** [code ISO, nom français, nom anglais, indicatif, monnaie ISO, capitale], triés par nom français. */
export const WORLD_COUNTRIES: [code: string, nameFr: string, nameEn: string, dialCode: string, currency: string, capital: string][] = [
  ["AF", "Afghanistan", "Afghanistan", "+93", "AFN", "Kabul"],
  ["ZA", "Afrique du Sud", "South Africa", "+27", "ZAR", "Pretoria"],
  ["AL", "Albanie", "Albania", "+355", "ALL", "Tirana"],
  ["DZ", "Algérie", "Algeria", "+213", "DZD", "Algiers"],
  ["DE", "Allemagne", "Germany", "+49", "EUR", "Berlin"],
  ["AD", "Andorre", "Andorra", "+376", "EUR", "Andorra la Vella"],
  ["AO", "Angola", "Angola", "+244", "AOA", "Luanda"],
  ["AI", "Anguilla", "Anguilla", "+1", "XCD", "The Valley"],
  ["AQ", "Antarctique", "Antarctica", "", "", ""],
  ["AG", "Antigua-et-Barbuda", "Antigua & Barbuda", "+1", "XCD", "St. John's"],
  ["SA", "Arabie saoudite", "Saudi Arabia", "+966", "SAR", "Riyadh"],
  ["AR", "Argentine", "Argentina", "+54", "ARS", "Buenos Aires"],
  ["AM", "Arménie", "Armenia", "+374", "AMD", "Yerevan"],
  ["AW", "Aruba", "Aruba", "+297", "AWG", "Oranjestad"],
  ["AU", "Australie", "Australia", "+61", "AUD", "Canberra"],
  ["AT", "Autriche", "Austria", "+43", "EUR", "Vienna"],
  ["AZ", "Azerbaïdjan", "Azerbaijan", "+994", "AZN", "Baku"],
  ["BS", "Bahamas", "Bahamas", "+1", "BSD", "Nassau"],
  ["BH", "Bahreïn", "Bahrain", "+973", "BHD", "Manama"],
  ["BD", "Bangladesh", "Bangladesh", "+880", "BDT", "Dhaka"],
  ["BB", "Barbade", "Barbados", "+1", "BBD", "Bridgetown"],
  ["BE", "Belgique", "Belgium", "+32", "EUR", "Brussels"],
  ["BZ", "Belize", "Belize", "+501", "BZD", "Belmopan"],
  ["BJ", "Bénin", "Benin", "+229", "XOF", "Porto-Novo"],
  ["BM", "Bermudes", "Bermuda", "+1", "BMD", "Hamilton"],
  ["BT", "Bhoutan", "Bhutan", "+975", "BTN", "Thimphu"],
  ["BY", "Biélorussie", "Belarus", "+375", "BYN", "Minsk"],
  ["BO", "Bolivie", "Bolivia", "+591", "BOB", "Sucre"],
  ["BA", "Bosnie-Herzégovine", "Bosnia & Herzegovina", "+387", "BAM", "Sarajevo"],
  ["BW", "Botswana", "Botswana", "+267", "BWP", "Gaborone"],
  ["BR", "Brésil", "Brazil", "+55", "BRL", "Brasilia"],
  ["BN", "Brunei", "Brunei", "+673", "BND", "Bandar Seri Begawan"],
  ["BG", "Bulgarie", "Bulgaria", "+359", "BGN", "Sofia"],
  ["BF", "Burkina Faso", "Burkina Faso", "+226", "XOF", "Ouagadougou"],
  ["BI", "Burundi", "Burundi", "+257", "BIF", "Gitega"],
  ["KH", "Cambodge", "Cambodia", "+855", "KHR", "Phnom Penh"],
  ["CM", "Cameroun", "Cameroon", "+237", "XAF", "Yaounde"],
  ["CA", "Canada", "Canada", "+1", "CAD", "Ottawa"],
  ["CV", "Cap-Vert", "Cape Verde", "+238", "CVE", "Praia"],
  ["CL", "Chili", "Chile", "+56", "CLP", "Santiago"],
  ["CN", "Chine", "China", "+86", "CNY", "Beijing"],
  ["CY", "Chypre", "Cyprus", "+357", "EUR", "Nicosia"],
  ["CO", "Colombie", "Colombia", "+57", "COP", "Bogota"],
  ["KM", "Comores", "Comoros", "+269", "KMF", "Moroni"],
  ["CG", "Congo-Brazzaville", "Congo - Brazzaville", "+242", "XAF", "Brazzaville"],
  ["CD", "Congo-Kinshasa", "Congo - Kinshasa", "+243", "CDF", "Kinshasa"],
  ["KP", "Corée du Nord", "North Korea", "+850", "KPW", "Pyongyang"],
  ["KR", "Corée du Sud", "South Korea", "+82", "KRW", "Seoul"],
  ["CR", "Costa Rica", "Costa Rica", "+506", "CRC", "San Jose"],
  ["CI", "Côte d'Ivoire", "Côte d'Ivoire", "+225", "XOF", "Yamoussoukro"],
  ["HR", "Croatie", "Croatia", "+385", "EUR", "Zagreb"],
  ["CU", "Cuba", "Cuba", "+53", "CUP", "Havana"],
  ["CW", "Curaçao", "Curaçao", "+599", "XCG", " Willemstad"],
  ["DK", "Danemark", "Denmark", "+45", "DKK", "Copenhagen"],
  ["DJ", "Djibouti", "Djibouti", "+253", "DJF", "Djibouti"],
  ["DM", "Dominique", "Dominica", "+1", "XCD", "Roseau"],
  ["EG", "Égypte", "Egypt", "+20", "EGP", "Cairo"],
  ["AE", "Émirats arabes unis", "United Arab Emirates", "+971", "AED", "Abu Dhabi"],
  ["EC", "Équateur", "Ecuador", "+593", "USD", "Quito"],
  ["ER", "Érythrée", "Eritrea", "+291", "ERN", "Asmara"],
  ["ES", "Espagne", "Spain", "+34", "EUR", "Madrid"],
  ["EE", "Estonie", "Estonia", "+372", "EUR", "Tallinn"],
  ["SZ", "Eswatini", "Eswatini", "+268", "SZL", "Mbabane"],
  ["VA", "État de la Cité du Vatican", "Vatican City", "+379", "EUR", "Vatican City"],
  ["US", "États-Unis", "United States", "+1", "USD", "Washington"],
  ["ET", "Éthiopie", "Ethiopia", "+251", "ETB", "Addis Ababa"],
  ["FJ", "Fidji", "Fiji", "+679", "FJD", "Suva"],
  ["FI", "Finlande", "Finland", "+358", "EUR", "Helsinki"],
  ["FR", "France", "France", "+33", "EUR", "Paris"],
  ["GA", "Gabon", "Gabon", "+241", "XAF", "Libreville"],
  ["GM", "Gambie", "Gambia", "+220", "GMD", "Banjul"],
  ["GE", "Géorgie", "Georgia", "+995", "GEL", "Tbilisi"],
  ["GS", "Géorgie du Sud-et-les Îles Sandwich du Sud", "South Georgia & South Sandwich Islands", "", "GBP", "Grytviken"],
  ["GH", "Ghana", "Ghana", "+233", "GHS", "Accra"],
  ["GI", "Gibraltar", "Gibraltar", "+350", "GIP", "Gibraltar"],
  ["GR", "Grèce", "Greece", "+30", "EUR", "Athens"],
  ["GD", "Grenade", "Grenada", "+1", "XCD", "St. George's"],
  ["GL", "Groenland", "Greenland", "+299", "DKK", "Nuuk"],
  ["GP", "Guadeloupe", "Guadeloupe", "+590", "EUR", "Basse-Terre"],
  ["GU", "Guam", "Guam", "+1", "USD", "Hagatna"],
  ["GT", "Guatemala", "Guatemala", "+502", "GTQ", "Guatemala City"],
  ["GG", "Guernesey", "Guernsey", "+44", "GBP", "St Peter Port"],
  ["GN", "Guinée", "Guinea", "+224", "GNF", "Conakry"],
  ["GQ", "Guinée équatoriale", "Equatorial Guinea", "+240", "XAF", "Ciudad de la Paz"],
  ["GW", "Guinée-Bissau", "Guinea-Bissau", "+245", "XOF", "Bissau"],
  ["GY", "Guyana", "Guyana", "+592", "GYD", "Georgetown"],
  ["GF", "Guyane française", "French Guiana", "+594", "EUR", "Cayenne"],
  ["HT", "Haïti", "Haiti", "+509", "HTG", "Port-au-Prince"],
  ["HN", "Honduras", "Honduras", "+504", "HNL", "Tegucigalpa"],
  ["HU", "Hongrie", "Hungary", "+36", "HUF", "Budapest"],
  ["BV", "Île Bouvet", "Bouvet Island", "", "NOK", ""],
  ["CX", "Île Christmas", "Christmas Island", "+61", "AUD", "Flying Fish Cove"],
  ["IM", "Île de Man", "Isle of Man", "+44", "GBP", "Douglas"],
  ["NF", "Île Norfolk", "Norfolk Island", "+672", "AUD", "Kingston"],
  ["AX", "Îles Åland", "Åland Islands", "+358", "EUR", "Mariehamn"],
  ["KY", "Îles Caïmans", "Cayman Islands", "+1", "KYD", "George Town"],
  ["CC", "Îles Cocos", "Cocos (Keeling) Islands", "+61", "AUD", "West Island"],
  ["CK", "Îles Cook", "Cook Islands", "+682", "NZD", "Avarua"],
  ["FO", "Îles Féroé", "Faroe Islands", "+298", "DKK", "Torshavn"],
  ["HM", "Îles Heard-et-MacDonald", "Heard & McDonald Islands", "", "AUD", ""],
  ["FK", "Îles Malouines", "Falkland Islands", "+500", "FKP", "Stanley"],
  ["MP", "Îles Mariannes du Nord", "Northern Mariana Islands", "+1", "USD", "Saipan"],
  ["MH", "Îles Marshall", "Marshall Islands", "+692", "USD", "Majuro"],
  ["UM", "Îles mineures éloignées des États-Unis", "U.S. Outlying Islands", "+1", "USD", ""],
  ["PN", "Îles Pitcairn", "Pitcairn Islands", "+870", "NZD", "Adamstown"],
  ["SB", "Îles Salomon", "Solomon Islands", "+677", "SBD", "Honiara"],
  ["TC", "Îles Turques-et-Caïques", "Turks & Caicos Islands", "+1", "USD", "Cockburn Town"],
  ["VG", "Îles Vierges britanniques", "British Virgin Islands", "+1", "USD", "Road Town"],
  ["VI", "Îles Vierges des États-Unis", "U.S. Virgin Islands", "+1", "USD", "Charlotte Amalie"],
  ["IN", "Inde", "India", "+91", "INR", "New Delhi"],
  ["ID", "Indonésie", "Indonesia", "+62", "IDR", "Jakarta"],
  ["IQ", "Irak", "Iraq", "+964", "IQD", "Baghdad"],
  ["IR", "Iran", "Iran", "+98", "IRR", "Tehran"],
  ["IE", "Irlande", "Ireland", "+353", "EUR", "Dublin"],
  ["IS", "Islande", "Iceland", "+354", "ISK", "Reykjavik"],
  ["IL", "Israël", "Israel", "+972", "ILS", "Jerusalem"],
  ["IT", "Italie", "Italy", "+39", "EUR", "Rome"],
  ["JM", "Jamaïque", "Jamaica", "+1", "JMD", "Kingston"],
  ["JP", "Japon", "Japan", "+81", "JPY", "Tokyo"],
  ["JE", "Jersey", "Jersey", "+44", "GBP", "Saint Helier"],
  ["JO", "Jordanie", "Jordan", "+962", "JOD", "Amman"],
  ["KZ", "Kazakhstan", "Kazakhstan", "+7", "KZT", "Nur-Sultan"],
  ["KE", "Kenya", "Kenya", "+254", "KES", "Nairobi"],
  ["KG", "Kirghizstan", "Kyrgyzstan", "+996", "KGS", "Bishkek"],
  ["KI", "Kiribati", "Kiribati", "+686", "AUD", "Tarawa"],
  ["XK", "Kosovo", "Kosovo", "", "EUR", "Pristina"],
  ["KW", "Koweït", "Kuwait", "+965", "KWD", "Kuwait City"],
  ["RE", "La Réunion", "Réunion", "+262", "EUR", "Saint-Denis"],
  ["LA", "Laos", "Laos", "+856", "LAK", "Vientiane"],
  ["LS", "Lesotho", "Lesotho", "+266", "LSL", "Maseru"],
  ["LV", "Lettonie", "Latvia", "+371", "EUR", "Riga"],
  ["LB", "Liban", "Lebanon", "+961", "LBP", "Beirut"],
  ["LR", "Liberia", "Liberia", "+231", "LRD", "Monrovia"],
  ["LY", "Libye", "Libya", "+218", "LYD", "Tripoli"],
  ["LI", "Liechtenstein", "Liechtenstein", "+423", "CHF", "Vaduz"],
  ["LT", "Lituanie", "Lithuania", "+370", "EUR", "Vilnius"],
  ["LU", "Luxembourg", "Luxembourg", "+352", "EUR", "Luxembourg"],
  ["MK", "Macédoine du Nord", "North Macedonia", "+389", "MKD", "Skopje"],
  ["MG", "Madagascar", "Madagascar", "+261", "MGA", "Antananarivo"],
  ["MY", "Malaisie", "Malaysia", "+60", "MYR", "Kuala Lumpur"],
  ["MW", "Malawi", "Malawi", "+265", "MWK", "Lilongwe"],
  ["MV", "Maldives", "Maldives", "+960", "MVR", "Male"],
  ["ML", "Mali", "Mali", "+223", "XOF", "Bamako"],
  ["MT", "Malte", "Malta", "+356", "EUR", "Valletta"],
  ["MA", "Maroc", "Morocco", "+212", "MAD", "Rabat"],
  ["MQ", "Martinique", "Martinique", "+596", "EUR", "Fort-de-France"],
  ["MU", "Maurice", "Mauritius", "+230", "MUR", "Port Louis"],
  ["MR", "Mauritanie", "Mauritania", "+222", "MRU", "Nouakchott"],
  ["YT", "Mayotte", "Mayotte", "+262", "EUR", "Mamoudzou"],
  ["MX", "Mexique", "Mexico", "+52", "MXN", "Mexico City"],
  ["FM", "Micronésie", "Micronesia", "+691", "USD", "Palikir"],
  ["MD", "Moldavie", "Moldova", "+373", "MDL", "Chisinau"],
  ["MC", "Monaco", "Monaco", "+377", "EUR", "Monaco"],
  ["MN", "Mongolie", "Mongolia", "+976", "MNT", "Ulaanbaatar"],
  ["ME", "Monténégro", "Montenegro", "+382", "EUR", "Podgorica"],
  ["MS", "Montserrat", "Montserrat", "+1", "XCD", "Plymouth"],
  ["MZ", "Mozambique", "Mozambique", "+258", "MZN", "Maputo"],
  ["MM", "Myanmar (Birmanie)", "Myanmar (Burma)", "+95", "MMK", "Nay Pyi Taw"],
  ["NA", "Namibie", "Namibia", "+264", "NAD", "Windhoek"],
  ["NR", "Nauru", "Nauru", "+674", "AUD", "Yaren"],
  ["NP", "Népal", "Nepal", "+977", "NPR", "Kathmandu"],
  ["NI", "Nicaragua", "Nicaragua", "+505", "NIO", "Managua"],
  ["NE", "Niger", "Niger", "+227", "XOF", "Niamey"],
  ["NG", "Nigeria", "Nigeria", "+234", "NGN", "Abuja"],
  ["NU", "Niue", "Niue", "+683", "NZD", "Alofi"],
  ["NO", "Norvège", "Norway", "+47", "NOK", "Oslo"],
  ["NC", "Nouvelle-Calédonie", "New Caledonia", "+687", "XPF", "Noumea"],
  ["NZ", "Nouvelle-Zélande", "New Zealand", "+64", "NZD", "Wellington"],
  ["OM", "Oman", "Oman", "+968", "OMR", "Muscat"],
  ["UG", "Ouganda", "Uganda", "+256", "UGX", "Kampala"],
  ["UZ", "Ouzbékistan", "Uzbekistan", "+998", "UZS", "Tashkent"],
  ["PK", "Pakistan", "Pakistan", "+92", "PKR", "Islamabad"],
  ["PW", "Palaos", "Palau", "+680", "USD", "Melekeok"],
  ["PA", "Panama", "Panama", "+507", "PAB", "Panama City"],
  ["PG", "Papouasie-Nouvelle-Guinée", "Papua New Guinea", "+675", "PGK", "Port Moresby"],
  ["PY", "Paraguay", "Paraguay", "+595", "PYG", "Asuncion"],
  ["NL", "Pays-Bas", "Netherlands", "+31", "EUR", "Amsterdam"],
  ["BQ", "Pays-Bas caribéens", "Caribbean Netherlands", "+599", "USD", ""],
  ["PE", "Pérou", "Peru", "+51", "PEN", "Lima"],
  ["PH", "Philippines", "Philippines", "+63", "PHP", "Manila"],
  ["PL", "Pologne", "Poland", "+48", "PLN", "Warsaw"],
  ["PF", "Polynésie française", "French Polynesia", "+689", "XPF", "Papeete"],
  ["PR", "Porto Rico", "Puerto Rico", "+1", "USD", "San Juan"],
  ["PT", "Portugal", "Portugal", "+351", "EUR", "Lisbon"],
  ["QA", "Qatar", "Qatar", "+974", "QAR", "Doha"],
  ["HK", "R.A.S. chinoise de Hong Kong", "Hong Kong SAR China", "+852", "HKD", "Hong Kong"],
  ["MO", "R.A.S. chinoise de Macao", "Macao SAR China", "+853", "MOP", "Macao"],
  ["CF", "République centrafricaine", "Central African Republic", "+236", "XAF", "Bangui"],
  ["DO", "République dominicaine", "Dominican Republic", "+1", "DOP", "Santo Domingo"],
  ["RO", "Roumanie", "Romania", "+40", "RON", "Bucharest"],
  ["GB", "Royaume-Uni", "United Kingdom", "+44", "GBP", "London"],
  ["RU", "Russie", "Russia", "+7", "RUB", "Moscow"],
  ["RW", "Rwanda", "Rwanda", "+250", "RWF", "Kigali"],
  ["EH", "Sahara occidental", "Western Sahara", "+212", "MAD", "El-Aaiun"],
  ["BL", "Saint-Barthélemy", "St. Barthélemy", "+590", "EUR", "Gustavia"],
  ["KN", "Saint-Christophe-et-Niévès", "St. Kitts & Nevis", "+1", "XCD", "Basseterre"],
  ["SM", "Saint-Marin", "San Marino", "+378", "EUR", "San Marino"],
  ["MF", "Saint-Martin", "St. Martin", "+590", "EUR", "Marigot"],
  ["SX", "Saint-Martin (partie néerlandaise)", "Sint Maarten", "+599", "XCG", "Philipsburg"],
  ["PM", "Saint-Pierre-et-Miquelon", "St. Pierre & Miquelon", "+508", "EUR", "Saint-Pierre"],
  ["VC", "Saint-Vincent-et-les Grenadines", "St. Vincent & Grenadines", "+1", "XCD", "Kingstown"],
  ["SH", "Sainte-Hélène", "St. Helena", "+290", "SHP", "Jamestown"],
  ["LC", "Sainte-Lucie", "St. Lucia", "+1", "XCD", "Castries"],
  ["SV", "Salvador", "El Salvador", "+503", "USD", "San Salvador"],
  ["WS", "Samoa", "Samoa", "+685", "WST", "Apia"],
  ["AS", "Samoa américaines", "American Samoa", "+1", "USD", "Pago Pago"],
  ["ST", "Sao Tomé-et-Principe", "São Tomé & Príncipe", "+239", "STN", "Sao Tome"],
  ["SN", "Sénégal", "Senegal", "+221", "XOF", "Dakar"],
  ["RS", "Serbie", "Serbia", "+381", "RSD", "Belgrade"],
  ["SC", "Seychelles", "Seychelles", "+248", "SCR", "Victoria"],
  ["SL", "Sierra Leone", "Sierra Leone", "+232", "SLE", "Freetown"],
  ["SG", "Singapour", "Singapore", "+65", "SGD", "Singapore"],
  ["SK", "Slovaquie", "Slovakia", "+421", "EUR", "Bratislava"],
  ["SI", "Slovénie", "Slovenia", "+386", "EUR", "Ljubljana"],
  ["SO", "Somalie", "Somalia", "+252", "SOS", "Mogadishu"],
  ["SD", "Soudan", "Sudan", "+249", "SDG", "Khartoum"],
  ["SS", "Soudan du Sud", "South Sudan", "+211", "SSP", "Juba"],
  ["LK", "Sri Lanka", "Sri Lanka", "+94", "LKR", "Colombo"],
  ["SE", "Suède", "Sweden", "+46", "SEK", "Stockholm"],
  ["CH", "Suisse", "Switzerland", "+41", "CHF", "Bern"],
  ["SR", "Suriname", "Suriname", "+597", "SRD", "Paramaribo"],
  ["SJ", "Svalbard et Jan Mayen", "Svalbard & Jan Mayen", "+47", "NOK", "Longyearbyen"],
  ["SY", "Syrie", "Syria", "+963", "SYP", "Damascus"],
  ["TJ", "Tadjikistan", "Tajikistan", "+992", "TJS", "Dushanbe"],
  ["TW", "Taïwan", "Taiwan", "+886", "TWD", "Taipei"],
  ["TZ", "Tanzanie", "Tanzania", "+255", "TZS", "Dodoma"],
  ["TD", "Tchad", "Chad", "+235", "XAF", "N'Djamena"],
  ["CZ", "Tchéquie", "Czechia", "+420", "CZK", "Prague"],
  ["TF", "Terres australes françaises", "French Southern Territories", "", "EUR", "Port-aux-Francais"],
  ["IO", "Territoire britannique de l'océan Indien", "British Indian Ocean Territory", "+246", "USD", "Diego Garcia"],
  ["PS", "Territoires palestiniens", "Palestinian Territories", "+970", "ILS", "East Jerusalem"],
  ["TH", "Thaïlande", "Thailand", "+66", "THB", "Bangkok"],
  ["TL", "Timor oriental", "Timor-Leste", "+670", "USD", "Dili"],
  ["TG", "Togo", "Togo", "+228", "XOF", "Lome"],
  ["TK", "Tokelau", "Tokelau", "+690", "NZD", ""],
  ["TO", "Tonga", "Tonga", "+676", "TOP", "Nuku'alofa"],
  ["TT", "Trinité-et-Tobago", "Trinidad & Tobago", "+1", "TTD", "Port of Spain"],
  ["TN", "Tunisie", "Tunisia", "+216", "TND", "Tunis"],
  ["TM", "Turkménistan", "Turkmenistan", "+993", "TMT", "Ashgabat"],
  ["TR", "Turquie", "Türkiye", "+90", "TRY", "Ankara"],
  ["TV", "Tuvalu", "Tuvalu", "+688", "AUD", "Funafuti"],
  ["UA", "Ukraine", "Ukraine", "+380", "UAH", "Kyiv"],
  ["UY", "Uruguay", "Uruguay", "+598", "UYU", "Montevideo"],
  ["VU", "Vanuatu", "Vanuatu", "+678", "VUV", "Port Vila"],
  ["VE", "Venezuela", "Venezuela", "+58", "VES", "Caracas"],
  ["VN", "Viêt Nam", "Vietnam", "+84", "VND", "Hanoi"],
  ["WF", "Wallis-et-Futuna", "Wallis & Futuna", "+681", "XPF", "Mata Utu"],
  ["YE", "Yémen", "Yemen", "+967", "YER", "Sanaa"],
  ["ZM", "Zambie", "Zambia", "+260", "ZMW", "Lusaka"],
  ["ZW", "Zimbabwe", "Zimbabwe", "+263", "ZWG", "Harare"],
];

/** [code ISO, nom français, symbole] des monnaies des pays ci-dessus, triées par nom. */
export const WORLD_CURRENCIES: [code: string, nameFr: string, symbol: string][] = [
  ["AFN", "Afghani afghan", "؋"],
  ["MGA", "Ariary malgache", "Ar"],
  ["THB", "Baht thaïlandais", "฿"],
  ["PAB", "Balboa panaméen", "PAB"],
  ["ETB", "Birr éthiopien", "ETB"],
  ["VES", "Bolivar vénézuélien", "VES"],
  ["BOB", "Boliviano bolivien", "Bs"],
  ["GHS", "Cédi ghanéen", "GH₵"],
  ["CRC", "Colón costaricain", "₡"],
  ["NIO", "Córdoba oro nicaraguayen", "$C"],
  ["DKK", "Couronne danoise", "kr"],
  ["ISK", "Couronne islandaise", "kr"],
  ["NOK", "Couronne norvégienne", "kr"],
  ["SEK", "Couronne suédoise", "kr"],
  ["CZK", "Couronne tchèque", "Kč"],
  ["GMD", "Dalasi gambien", "GMD"],
  ["MKD", "Denar macédonien", "MKD"],
  ["DZD", "Dinar algérien", "DZD"],
  ["BHD", "Dinar bahreïni", "BHD"],
  ["IQD", "Dinar irakien", "IQD"],
  ["JOD", "Dinar jordanien", "JOD"],
  ["KWD", "Dinar koweïtien", "KWD"],
  ["LYD", "Dinar libyen", "LYD"],
  ["RSD", "Dinar serbe", "RSD"],
  ["TND", "Dinar tunisien", "TND"],
  ["AED", "Dirham des Émirats arabes unis", "AED"],
  ["MAD", "Dirham marocain", "MAD"],
  ["STN", "Dobra santoméen", "Db"],
  ["AUD", "Dollar australien", "$"],
  ["BSD", "Dollar bahaméen", "$"],
  ["BBD", "Dollar barbadien", "$"],
  ["BZD", "Dollar bélizéen", "$"],
  ["BMD", "Dollar bermudien", "$"],
  ["BND", "Dollar brunéien", "$"],
  ["CAD", "Dollar canadien", "$"],
  ["HKD", "Dollar de Hong Kong", "$"],
  ["SGD", "Dollar de Singapour", "$"],
  ["TTD", "Dollar de Trinité-et-Tobago", "$"],
  ["XCD", "Dollar des Caraïbes orientales", "$"],
  ["USD", "Dollar des États-Unis", "$"],
  ["KYD", "Dollar des îles Caïmans", "$"],
  ["SBD", "Dollar des îles Salomon", "$"],
  ["GYD", "Dollar du Guyana", "$"],
  ["FJD", "Dollar fidjien", "$"],
  ["JMD", "Dollar jamaïcain", "$"],
  ["LRD", "Dollar libérien", "$"],
  ["NAD", "Dollar namibien", "$"],
  ["NZD", "Dollar néo-zélandais", "$"],
  ["SRD", "Dollar surinamais", "$"],
  ["VND", "Dông vietnamien", "₫"],
  ["AMD", "Dram arménien", "֏"],
  ["CVE", "Escudo capverdien", "CVE"],
  ["EUR", "Euro", "€"],
  ["AWG", "Florin arubais", "AWG"],
  ["XCG", "Florin caribéen", "Cg."],
  ["HUF", "Forint hongrois", "Ft"],
  ["BIF", "Franc burundais", "BIF"],
  ["XAF", "Franc CFA (CEMAC)", "FCFA"],
  ["XOF", "Franc CFA (UEMOA)", "FCFA"],
  ["XPF", "Franc CFP", "FCFP"],
  ["KMF", "Franc comorien", "FC"],
  ["CDF", "Franc congolais", "CDF"],
  ["DJF", "Franc djiboutien", "DJF"],
  ["GNF", "Franc guinéen", "FG"],
  ["RWF", "Franc rwandais", "FR"],
  ["CHF", "Franc suisse", "CHF"],
  ["HTG", "Gourde haïtienne", "HTG"],
  ["PYG", "Guaraní paraguayen", "₲"],
  ["UAH", "Hryvnia ukrainienne", "₴"],
  ["PGK", "Kina papouan-néo-guinéen", "PGK"],
  ["LAK", "Kip laotien", "₭"],
  ["MWK", "Kwacha malawite", "MWK"],
  ["ZMW", "Kwacha zambien", "Kw"],
  ["AOA", "Kwanza angolais", "Kz"],
  ["MMK", "Kyat myanmarais", "K"],
  ["GEL", "Lari géorgien", "₾"],
  ["ALL", "Lek albanais", "ALL"],
  ["HNL", "Lempira hondurien", "L"],
  ["SLE", "Leone sierra-léonais", "SLE"],
  ["MDL", "Leu moldave", "MDL"],
  ["RON", "Leu roumain", "L"],
  ["BGN", "Lev bulgare", "BGN"],
  ["SZL", "Lilangeni swazi", "SZL"],
  ["GIP", "Livre de Gibraltar", "£"],
  ["SHP", "Livre de Sainte-Hélène", "£"],
  ["FKP", "Livre des îles Malouines", "£"],
  ["EGP", "Livre égyptienne", "£E"],
  ["LBP", "Livre libanaise", "£L"],
  ["SDG", "Livre soudanaise", "SDG"],
  ["GBP", "Livre sterling", "£"],
  ["SSP", "Livre sud-soudanaise", "£"],
  ["SYP", "Livre syrienne", "£"],
  ["TRY", "Livre turque", "₺"],
  ["LSL", "Loti lesothan", "LSL"],
  ["AZN", "Manat azéri", "₼"],
  ["BAM", "Mark convertible bosniaque", "KM"],
  ["MZN", "Metical mozambicain", "MZN"],
  ["ERN", "Nafka érythréen", "ERN"],
  ["NGN", "Naira nigérian", "₦"],
  ["BTN", "Ngultrum bouthanais", "BTN"],
  ["TWD", "Nouveau dollar taïwanais", "NT$"],
  ["TMT", "Nouveau manat turkmène", "TMT"],
  ["ILS", "Nouveau shekel israélien", "₪"],
  ["ZWG", "Or du Zimbabwe", "ZWG"],
  ["MRU", "Ouguiya mauritanien", "MRU"],
  ["TOP", "Pa’anga tongan", "$T"],
  ["MOP", "Pataca macanaise", "MOP"],
  ["ARS", "Peso argentin", "$"],
  ["CLP", "Peso chilien", "$"],
  ["COP", "Peso colombien", "$"],
  ["CUP", "Peso cubain", "$"],
  ["DOP", "Peso dominicain", "$"],
  ["MXN", "Peso mexicain", "$"],
  ["PHP", "Peso philippin", "₱"],
  ["UYU", "Peso uruguayen", "$"],
  ["BWP", "Pula botswanais", "P"],
  ["GTQ", "Quetzal guatémaltèque", "Q"],
  ["ZAR", "Rand sud-africain", "R"],
  ["BRL", "Réal brésilien", "R$"],
  ["KHR", "Riel cambodgien", "៛"],
  ["MYR", "Ringgit malais", "RM"],
  ["IRR", "Riyal iranien", "IRR"],
  ["OMR", "Riyal omanais", "OMR"],
  ["QAR", "Riyal qatari", "QAR"],
  ["SAR", "Riyal saoudien", "SAR"],
  ["YER", "Riyal yéménite", "YER"],
  ["BYN", "Rouble biélorusse", "р."],
  ["RUB", "Rouble russe", "₽"],
  ["SCR", "Roupie des Seychelles", "SCR"],
  ["INR", "Roupie indienne", "₹"],
  ["IDR", "Roupie indonésienne", "Rp"],
  ["MUR", "Roupie mauricienne", "Rs"],
  ["NPR", "Roupie népalaise", "Rs"],
  ["PKR", "Roupie pakistanaise", "Rs"],
  ["LKR", "Roupie srilankaise", "Rs"],
  ["MVR", "Rufiyaa maldivienne", "MVR"],
  ["KES", "Shilling kényan", "KES"],
  ["UGX", "Shilling ougandais", "UGX"],
  ["SOS", "Shilling somalien", "SOS"],
  ["TZS", "Shilling tanzanien", "TZS"],
  ["PEN", "Sol péruvien", "PEN"],
  ["KGS", "Som kirghize", "⃀"],
  ["TJS", "Somoni tadjik", "TJS"],
  ["UZS", "Sum ouzbek", "UZS"],
  ["BDT", "Taka bangladeshi", "৳"],
  ["WST", "Tala samoan", "$WS"],
  ["KZT", "Tenge kazakh", "₸"],
  ["MNT", "Tugrik mongol", "₮"],
  ["VUV", "Vatu vanuatuan", "VUV"],
  ["KPW", "Won nord-coréen", "₩"],
  ["KRW", "Won sud-coréen", "₩"],
  ["JPY", "Yen japonais", "¥"],
  ["CNY", "Yuan renminbi chinois", "¥"],
  ["PLN", "Zloty polonais", "zł"],
];
